### ISSUE TITLE
How to link between main report and subreports

### ISSUE THREAD

**Issue by voisardf** [sbrunner/crdppf#1]
@sbrunner : I get the subreports table and table2 to work using your config with nested datasources as in your config, thanks!

But now the issue is, how to link the datasources between the main report (pdfReport) and the two subreport levels (table, table2) when I replace
https://github.com/sbrunner/crdppf/blob/master/config.yaml#L5
with 
    \* reportTemplate: pdfReport.jrxml
how do I have to link the datasource and define the fields? 

I either have an complet titlepage with empty fields in the subreports or just the subreports without mainpage:
[mainreport.pdf](https://github.com/sbrunner/crdppf/files/461938/mainreport.pdf)
[subreports.pdf](https://github.com/sbrunner/crdppf/files/461953/subreports.pdf)

the result should be something like this:
[document.pdf](https://github.com/sbrunner/crdppf/files/461950/document.pdf)

Thanks for your help, I think we are almost there...

**Comment by voisardf** [comment]
My configuration:
[20160908_crdppf.zip](https://github.com/sbrunner/crdppf/files/461965/20160908_crdppf.zip)

**Comment by sbrunner** [comment]
Does it do what you want?
https://github.com/sbrunner/crdppf/commit/18c71456dae8b936c7456973088d0da28a44361f
