### ISSUE TITLE
PDF Fonts and text in bold

### ISSUE THREAD

**Issue by voisardf** [sbrunner/crdppf#2]
I don't know how to make sure the Cadastra Font is used in the templates and the text printed in bold where it's set to isbold = "true"...
Do I have to embed the font and if so how is it done exactly? 

thanks for having a look into it!

**Comment by marionb** [comment]
I am assuming that "Cadastra" is not a standard font and might not be available on all systems. You can ship the font with the print file.

To do this you can add a jar containing the font. To extract a jar from an available font file there are some instructions [here](http://community.jaspersoft.com/wiki/custom-font-font-extension)

From this link above you can follow the instruction to fist add the font in jasperreports from a .tff (Create the Font Extension) and then extract it in to a .jar file (Export the Font Extension)

Next add the .jar file in the print under `print/WEB-INF/lib/`

In this way the font will be included in the PDF and should be applied independent of the system.

**Comment by voisardf** [comment]
Thanks, I finally got this one, using the FontExtension rather than 'styles' :) 
the jar is attached.

[Cadastra.zip](https://github.com/sbrunner/crdppf/files/663035/Cadastra.zip)
